UIButton *button13 = [UIButton buttonWithType:UIButtonTypeRoundedRect];
button13.frame = CGRectMake(152.0, 301.0, 72.0, 37.0);
button13.adjustsImageWhenDisabled = YES;
button13.adjustsImageWhenHighlighted = YES;
button13.alpha = 1.000;
button13.autoresizesSubviews = YES;
button13.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
button13.clearsContextBeforeDrawing = YES;
button13.clipsToBounds = NO;
button13.contentHorizontalAlignment = UIControlContentHorizontalAlignmentCenter;
button13.contentMode = UIViewContentModeScaleToFill;
button13.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
button13.contentVerticalAlignment = UIControlContentVerticalAlignmentCenter;
button13.enabled = YES;
button13.hidden = NO;
button13.highlighted = NO;
button13.multipleTouchEnabled = NO;
button13.opaque = NO;
button13.reversesTitleShadowWhenHighlighted = NO;
button13.selected = NO;
button13.showsTouchWhenHighlighted = NO;
button13.tag = 0;
button13.titleLabel.lineBreakMode = UILineBreakModeMiddleTruncation;
button13.titleLabel.shadowOffset = CGSizeMake(0.0, 0.0);
button13.userInteractionEnabled = YES;
[button13 setTitleColor:[UIColor colorWithRed:0.196 green:0.310 blue:0.522 alpha:1.000] forState:UIControlStateNormal];
[button13 setTitleColor:[UIColor colorWithWhite:1.000 alpha:1.000] forState:UIControlStateHighlighted];
[button13 setTitleShadowColor:[UIColor colorWithWhite:0.500 alpha:1.000] forState:UIControlStateNormal];

UITableViewCell *tableviewcell3 = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"UITableViewCellReuseIdentifier"];
tableviewcell3.frame = CGRectMake(20.0, 70.0, 280.0, 50.0);
tableviewcell3.accessoryType = UITableViewCellAccessoryNone;
tableviewcell3.alpha = 1.000;
tableviewcell3.autoresizesSubviews = YES;
tableviewcell3.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
tableviewcell3.clearsContextBeforeDrawing = YES;
tableviewcell3.clipsToBounds = NO;
tableviewcell3.contentMode = UIViewContentModeScaleToFill;
tableviewcell3.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
tableviewcell3.editingAccessoryType = UITableViewCellAccessoryNone;
tableviewcell3.hidden = NO;
tableviewcell3.indentationLevel = 0;
tableviewcell3.indentationWidth = 10.000;
tableviewcell3.multipleTouchEnabled = NO;
tableviewcell3.opaque = YES;
tableviewcell3.selectionStyle = UITableViewCellSelectionStyleBlue;
tableviewcell3.shouldIndentWhileEditing = YES;
tableviewcell3.showsReorderControl = NO;
tableviewcell3.tag = 0;
tableviewcell3.userInteractionEnabled = YES;

UIPickerView *pickerview7 = [[UIPickerView alloc] initWithFrame:CGRectMake(150.0, -86.0, 120.0, 216.0)];
pickerview7.frame = CGRectMake(150.0, -86.0, 120.0, 216.0);
pickerview7.alpha = 1.000;
pickerview7.autoresizesSubviews = YES;
pickerview7.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
pickerview7.clearsContextBeforeDrawing = YES;
pickerview7.clipsToBounds = NO;
pickerview7.contentMode = UIViewContentModeScaleToFill;
pickerview7.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
pickerview7.hidden = NO;
pickerview7.multipleTouchEnabled = NO;
pickerview7.opaque = YES;
pickerview7.showsSelectionIndicator = YES;
pickerview7.tag = 0;
pickerview7.userInteractionEnabled = YES;

UILabel *label14 = [[UILabel alloc] initWithFrame:CGRectMake(130.0, 376.0, 42.0, 21.0)];
label14.frame = CGRectMake(130.0, 376.0, 42.0, 21.0);
label14.adjustsFontSizeToFitWidth = YES;
label14.alpha = 1.000;
label14.autoresizesSubviews = YES;
label14.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label14.backgroundColor = [UIColor colorWithRed:0.966 green:0.000 blue:0.011 alpha:1.000];
label14.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label14.clearsContextBeforeDrawing = YES;
label14.clipsToBounds = YES;
label14.contentMode = UIViewContentModeLeft;
label14.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label14.enabled = YES;
label14.hidden = NO;
label14.lineBreakMode = UILineBreakModeTailTruncation;
label14.minimumFontSize = 10.000;
label14.multipleTouchEnabled = NO;
label14.numberOfLines = 1;
label14.opaque = NO;
label14.shadowOffset = CGSizeMake(0.0, -1.0);
label14.tag = 0;
label14.text = @"Label";
label14.textAlignment = UITextAlignmentLeft;
label14.textColor = [UIColor colorWithRed:0.000 green:0.000 blue:0.000 alpha:1.000];
label14.userInteractionEnabled = NO;

UILabel *label5 = [[UILabel alloc] initWithFrame:CGRectMake(155.0, 5.0, 120.0, 40.0)];
label5.frame = CGRectMake(155.0, 5.0, 120.0, 40.0);
label5.adjustsFontSizeToFitWidth = YES;
label5.alpha = 1.000;
label5.autoresizesSubviews = YES;
label5.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
label5.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
label5.clearsContextBeforeDrawing = YES;
label5.clipsToBounds = YES;
label5.contentMode = UIViewContentModeLeft;
label5.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
label5.enabled = YES;
label5.hidden = NO;
label5.lineBreakMode = UILineBreakModeTailTruncation;
label5.minimumFontSize = 10.000;
label5.multipleTouchEnabled = NO;
label5.numberOfLines = 1;
label5.opaque = NO;
label5.shadowOffset = CGSizeMake(0.0, -1.0);
label5.tag = 0;
label5.text = @"Label";
label5.textAlignment = UITextAlignmentLeft;
label5.textColor = [UIColor colorWithRed:0.966 green:0.000 blue:0.011 alpha:1.000];
label5.userInteractionEnabled = NO;

UIView *view1 = [[UIView alloc] initWithFrame:CGRectMake(0.0, 20.0, 320.0, 460.0)];
view1.frame = CGRectMake(0.0, 20.0, 320.0, 460.0);
view1.alpha = 1.000;
view1.autoresizesSubviews = YES;
view1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
view1.backgroundColor = [UIColor colorWithWhite:1.000 alpha:1.000];
view1.clearsContextBeforeDrawing = YES;
view1.clipsToBounds = NO;
view1.contentMode = UIViewContentModeScaleToFill;
view1.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
view1.hidden = NO;
view1.multipleTouchEnabled = NO;
view1.opaque = YES;
view1.tag = 0;
view1.userInteractionEnabled = YES;

UIButton *button12 = [UIButton buttonWithType:UIButtonTypeRoundedRect];
button12.frame = CGRectMake(81.0, 301.0, 72.0, 37.0);
button12.adjustsImageWhenDisabled = YES;
button12.adjustsImageWhenHighlighted = YES;
button12.alpha = 1.000;
button12.autoresizesSubviews = YES;
button12.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
button12.clearsContextBeforeDrawing = YES;
button12.clipsToBounds = NO;
button12.contentHorizontalAlignment = UIControlContentHorizontalAlignmentCenter;
button12.contentMode = UIViewContentModeScaleToFill;
button12.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
button12.contentVerticalAlignment = UIControlContentVerticalAlignmentCenter;
button12.enabled = YES;
button12.hidden = NO;
button12.highlighted = NO;
button12.multipleTouchEnabled = NO;
button12.opaque = NO;
button12.reversesTitleShadowWhenHighlighted = NO;
button12.selected = NO;
button12.showsTouchWhenHighlighted = NO;
button12.tag = 0;
button12.titleLabel.lineBreakMode = UILineBreakModeMiddleTruncation;
button12.titleLabel.shadowOffset = CGSizeMake(0.0, 0.0);
button12.userInteractionEnabled = YES;
[button12 setTitleColor:[UIColor colorWithRed:0.196 green:0.310 blue:0.522 alpha:1.000] forState:UIControlStateNormal];
[button12 setTitleColor:[UIColor colorWithWhite:1.000 alpha:1.000] forState:UIControlStateHighlighted];
[button12 setTitleShadowColor:[UIColor colorWithWhite:0.500 alpha:1.000] forState:UIControlStateNormal];

UITableView *tableview15 = [[UITableView alloc] initWithFrame:CGRectMake(-7.0, 70.0, 160.0, 230.0) style:UITableViewStylePlain];
tableview15.frame = CGRectMake(-7.0, 70.0, 160.0, 230.0);
tableview15.allowsSelectionDuringEditing = NO;
tableview15.alpha = 1.000;
tableview15.alwaysBounceHorizontal = NO;
tableview15.alwaysBounceVertical = YES;
tableview15.autoresizesSubviews = YES;
tableview15.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
tableview15.backgroundColor = [UIColor colorWithWhite:1.000 alpha:1.000];
tableview15.bounces = YES;
tableview15.bouncesZoom = YES;
tableview15.canCancelContentTouches = YES;
tableview15.clearsContextBeforeDrawing = YES;
tableview15.clipsToBounds = YES;
tableview15.contentMode = UIViewContentModeScaleToFill;
tableview15.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
tableview15.delaysContentTouches = YES;
tableview15.directionalLockEnabled = NO;
tableview15.hidden = NO;
tableview15.indicatorStyle = UIScrollViewIndicatorStyleDefault;
tableview15.maximumZoomScale = 1.000;
tableview15.minimumZoomScale = 1.000;
tableview15.multipleTouchEnabled = NO;
tableview15.opaque = YES;
tableview15.pagingEnabled = NO;
tableview15.rowHeight = 44;
tableview15.scrollEnabled = YES;
tableview15.sectionFooterHeight = 22;
tableview15.sectionHeaderHeight = 22;
tableview15.sectionIndexMinimumDisplayRowCount = 0;
tableview15.separatorStyle = UITableViewCellSeparatorStyleSingleLine;
tableview15.showsHorizontalScrollIndicator = YES;
tableview15.showsVerticalScrollIndicator = YES;
tableview15.tag = 0;
tableview15.userInteractionEnabled = YES;

UITableViewCell *tableviewcell6 = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"UITableViewCellReuseIdentifier"];
tableviewcell6.frame = CGRectMake(20.0, 210.0, 280.0, 50.0);
tableviewcell6.accessoryType = UITableViewCellAccessoryNone;
tableviewcell6.alpha = 1.000;
tableviewcell6.autoresizesSubviews = YES;
tableviewcell6.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
tableviewcell6.clearsContextBeforeDrawing = YES;
tableviewcell6.clipsToBounds = NO;
tableviewcell6.contentMode = UIViewContentModeScaleToFill;
tableviewcell6.contentStretch = CGRectFromString(@"{{0, 0}, {1, 1}}");
tableviewcell6.editingAccessoryType = UITableViewCellAccessoryNone;
tableviewcell6.hidden = NO;
tableviewcell6.indentationLevel = 0;
tableviewcell6.indentationWidth = 10.000;
tableviewcell6.multipleTouchEnabled = NO;
tableviewcell6.opaque = YES;
tableviewcell6.selectionStyle = UITableViewCellSelectionStyleBlue;
tableviewcell6.shouldIndentWhileEditing = YES;
tableviewcell6.showsReorderControl = NO;
tableviewcell6.tag = 0;
tableviewcell6.userInteractionEnabled = YES;

[tableviewcell3 addSubview:label5];
[view1 addSubview:tableviewcell3];
[tableviewcell6 addSubview:pickerview7];
[view1 addSubview:tableviewcell6];
[view1 addSubview:button12];
[view1 addSubview:button13];
[view1 addSubview:label14];
[view1 addSubview:tableview15];
